package com.dubu.model;

import java.util.Date;

public class BattleMeta {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mz_profile_tournament.id
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mz_profile_tournament.regdttm
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    private Date regdttm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mz_profile_tournament.status
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_profile_tournament.id
     *
     * @return the value of mz_profile_tournament.id
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_profile_tournament.id
     *
     * @param id the value for mz_profile_tournament.id
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_profile_tournament.regdttm
     *
     * @return the value of mz_profile_tournament.regdttm
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    public Date getRegdttm() {
        return regdttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_profile_tournament.regdttm
     *
     * @param regdttm the value for mz_profile_tournament.regdttm
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    public void setRegdttm(Date regdttm) {
        this.regdttm = regdttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_profile_tournament.status
     *
     * @return the value of mz_profile_tournament.status
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_profile_tournament.status
     *
     * @param status the value for mz_profile_tournament.status
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}