package com.dubu.model;

import java.io.Serializable;
import java.util.Date;

public class BattlerKey{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mz_profile_tournament_entry.battle_id
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    private Integer battleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mz_profile_tournament_entry.battle_rank
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    private Integer battleRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mz_profile_tournament_entry.regdttm
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    private Date regdttm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_profile_tournament_entry.battle_id
     *
     * @return the value of mz_profile_tournament_entry.battle_id
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    public Integer getBattleId() {
        return battleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_profile_tournament_entry.battle_id
     *
     * @param battleId the value for mz_profile_tournament_entry.battle_id
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    public void setBattleId(Integer battleId) {
        this.battleId = battleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_profile_tournament_entry.battle_rank
     *
     * @return the value of mz_profile_tournament_entry.battle_rank
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    public Integer getBattleRank() {
        return battleRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_profile_tournament_entry.battle_rank
     *
     * @param battleRank the value for mz_profile_tournament_entry.battle_rank
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    public void setBattleRank(Integer battleRank) {
        this.battleRank = battleRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_profile_tournament_entry.regdttm
     *
     * @return the value of mz_profile_tournament_entry.regdttm
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    public Date getRegdttm() {
        return regdttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_profile_tournament_entry.regdttm
     *
     * @param regdttm the value for mz_profile_tournament_entry.regdttm
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    public void setRegdttm(Date regdttm) {
        this.regdttm = regdttm;
    }
}