package com.dubu.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BattleMetaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    public BattleMetaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRegdttmIsNull() {
            addCriterion("regdttm is null");
            return (Criteria) this;
        }

        public Criteria andRegdttmIsNotNull() {
            addCriterion("regdttm is not null");
            return (Criteria) this;
        }

        public Criteria andRegdttmEqualTo(Date value) {
            addCriterion("regdttm =", value, "regdttm");
            return (Criteria) this;
        }

        public Criteria andRegdttmNotEqualTo(Date value) {
            addCriterion("regdttm <>", value, "regdttm");
            return (Criteria) this;
        }

        public Criteria andRegdttmGreaterThan(Date value) {
            addCriterion("regdttm >", value, "regdttm");
            return (Criteria) this;
        }

        public Criteria andRegdttmGreaterThanOrEqualTo(Date value) {
            addCriterion("regdttm >=", value, "regdttm");
            return (Criteria) this;
        }

        public Criteria andRegdttmLessThan(Date value) {
            addCriterion("regdttm <", value, "regdttm");
            return (Criteria) this;
        }

        public Criteria andRegdttmLessThanOrEqualTo(Date value) {
            addCriterion("regdttm <=", value, "regdttm");
            return (Criteria) this;
        }

        public Criteria andRegdttmIn(List<Date> values) {
            addCriterion("regdttm in", values, "regdttm");
            return (Criteria) this;
        }

        public Criteria andRegdttmNotIn(List<Date> values) {
            addCriterion("regdttm not in", values, "regdttm");
            return (Criteria) this;
        }

        public Criteria andRegdttmBetween(Date value1, Date value2) {
            addCriterion("regdttm between", value1, value2, "regdttm");
            return (Criteria) this;
        }

        public Criteria andRegdttmNotBetween(Date value1, Date value2) {
            addCriterion("regdttm not between", value1, value2, "regdttm");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 31 10:36:58 KST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}