package com.dubu.model;

public class RankerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mz_profile_tournament_target.mz_user_id
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    private Integer mzUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mz_profile_tournament_target.tournament_id
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    private Integer tournamentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_profile_tournament_target.mz_user_id
     *
     * @return the value of mz_profile_tournament_target.mz_user_id
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    public Integer getMzUserId() {
        return mzUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_profile_tournament_target.mz_user_id
     *
     * @param mzUserId the value for mz_profile_tournament_target.mz_user_id
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    public void setMzUserId(Integer mzUserId) {
        this.mzUserId = mzUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_profile_tournament_target.tournament_id
     *
     * @return the value of mz_profile_tournament_target.tournament_id
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    public Integer getTournamentId() {
        return tournamentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_profile_tournament_target.tournament_id
     *
     * @param tournamentId the value for mz_profile_tournament_target.tournament_id
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    public void setTournamentId(Integer tournamentId) {
        this.tournamentId = tournamentId;
    }
}