package com.dubu.model;

import org.springframework.web.servlet.ModelAndView;

import javax.validation.constraints.DecimalMax;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Date;

public class Ranker extends RankerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mz_profile_tournament_target.tournament_point
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
     @NotNull
      @DecimalMax(value = "100")
    private Integer tournamentPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mz_profile_tournament_target.status
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mz_profile_tournament_target.regdttm
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    private Date regdttm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mz_profile_tournament_target.moddttm
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    private Date moddttm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mz_profile_tournament_target.pkey_moddttm
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    private String pkeyModdttm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_profile_tournament_target.tournament_point
     *
     * @return the value of mz_profile_tournament_target.tournament_point
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */

    public Integer getTournamentPoint() {
        return tournamentPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_profile_tournament_target.tournament_point
     *
     * @param tournamentPoint the value for mz_profile_tournament_target.tournament_point
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    public void setTournamentPoint(Integer tournamentPoint) {
        this.tournamentPoint = tournamentPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_profile_tournament_target.status
     *
     * @return the value of mz_profile_tournament_target.status
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_profile_tournament_target.status
     *
     * @param status the value for mz_profile_tournament_target.status
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_profile_tournament_target.regdttm
     *
     * @return the value of mz_profile_tournament_target.regdttm
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    public Date getRegdttm() {
        return regdttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_profile_tournament_target.regdttm
     *
     * @param regdttm the value for mz_profile_tournament_target.regdttm
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    public void setRegdttm(Date regdttm) {
        this.regdttm = regdttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_profile_tournament_target.moddttm
     *
     * @return the value of mz_profile_tournament_target.moddttm
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    public Date getModdttm() {
        return moddttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_profile_tournament_target.moddttm
     *
     * @param moddttm the value for mz_profile_tournament_target.moddttm
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    public void setModdttm(Date moddttm) {
        this.moddttm = moddttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mz_profile_tournament_target.pkey_moddttm
     *
     * @return the value of mz_profile_tournament_target.pkey_moddttm
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    public String getPkeyModdttm() {
        return pkeyModdttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mz_profile_tournament_target.pkey_moddttm
     *
     * @param pkeyModdttm the value for mz_profile_tournament_target.pkey_moddttm
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    public void setPkeyModdttm(String pkeyModdttm) {
        this.pkeyModdttm = pkeyModdttm == null ? null : pkeyModdttm.trim();
    }
}