package com.dubu.dao;

import com.dubu.model.Battler;
import com.dubu.model.BattlerExample;
import com.dubu.model.BattlerKey;
import org.springframework.stereotype.Repository;

import java.util.List;

public interface BattlerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_entry
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    int countByExample(BattlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_entry
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    int deleteByExample(BattlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_entry
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    int deleteByPrimaryKey(BattlerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_entry
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    int insert(Battler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_entry
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    int insertSelective(Battler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_entry
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    List<Battler> selectByExample(BattlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_entry
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    Battler selectByPrimaryKey(BattlerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_entry
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    int updateByExampleSelective( Battler record,BattlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_entry
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    int updateByExample(Battler record, BattlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_entry
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    int updateByPrimaryKeySelective(Battler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_entry
     *
     * @mbggenerated Tue Dec 24 17:24:28 KST 2013
     */
    int updateByPrimaryKey(Battler record);


}