package com.dubu.dao;

import com.dubu.model.BattleMeta;
import com.dubu.model.BattleMetaExample;
import java.util.List;

public interface BattleMetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    int countByExample(BattleMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    int deleteByExample(BattleMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    int insert(BattleMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    int insertSelective(BattleMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    List<BattleMeta> selectByExample(BattleMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    BattleMeta selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    int updateByExampleSelective (BattleMeta record,  BattleMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    int updateByExample(BattleMeta record,  BattleMetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    int updateByPrimaryKeySelective(BattleMeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament
     *
     * @mbggenerated Tue Dec 31 10:36:58 KST 2013
     */
    int updateByPrimaryKey(BattleMeta record);
}