package com.dubu.dao;

import com.dubu.model.Ranker;
import com.dubu.model.RankerExample;
import com.dubu.model.RankerKey;
import java.util.List;


public interface RankerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_target
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    int countByExample(RankerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_target
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    int deleteByExample(RankerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_target
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    int deleteByPrimaryKey(RankerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_target
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    int insert(Ranker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_target
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    int insertSelective(Ranker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_target
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    List<Ranker> selectByExample(RankerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_target
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    Ranker selectByPrimaryKey(RankerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_target
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    int updateByExampleSelective(Ranker record,  RankerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_target
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    int updateByExample( Ranker record,  RankerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_target
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    int updateByPrimaryKeySelective(Ranker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mz_profile_tournament_target
     *
     * @mbggenerated Tue Dec 31 14:38:26 KST 2013
     */
    int updateByPrimaryKey(Ranker record);
}